global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - scheme: http
    timeout: 10s
    api_version: v1
    static_configs:
    - targets: []
scrape_configs:
  - job_name: "rate_limit_exceeded_total"
    metrics_path: /metrics
    honor_timestamps: true
    scheme: http
    static_configs:  
      - targets:  
        - host.docker.internal:8080