version: '3.4'

services:
  mars.web:
    image: ${DOCKER_REGISTRY-}marsweb
    build:
      context: .
      dockerfile: Mars.Web/Dockerfile
    environment: 
      - SeqServer=http://seq
      - ASPNETCORE_ENVIRONMENT=Development
    ports: 
      - 8080:80
      - 8081:443
    networks:
      - jaegernet

  seq:
    container_name: seq
    image: datalust/seq:latest
    ports:
      - "8888:80"
    volumes:
      - /datadrive:/data
    networks:
      - jaegernet
    environment:
      - ACCEPT_EULA=Y

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug
    networks:
      - jaegernet
    depends_on:
      - mars.web

  prometheus:
    image: ubuntu/prometheus
    container_name: dev_prometheus
    ports:
      - "30090:9090"
    environment:
      - TZ=UTC
    networks:
      - jaegernet
    volumes:
      - ./prom/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: dev_grafana
    ports:
      - "30091:3000"
    networks:
      - jaegernet
    volumes:
      - ./grafana-data/data:/var/lib/grafana

networks:
  jaegernet: